### ISSUE TITLE
Feedback: API tutorial 4 - Process query result data and save to file

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/examples#175]
See comment in #165  by @TilmanKie: 

_Code at setup token did not work
And the last code at "Create a .xlsx file with...." did not work (ModuleNotFoundError: No module named 'xlsxwriter')_

**Comment by flohrreija-oeko** [comment]
I am not sure to which tutorial this ticket corresponds to as API tutorial 4 does not exist. Before, there was a link to API tutorial 01(https://openenergyplatform.github.io/academy/tutorials/01_api/01_api_download/) with the title of this link (but it was already unclear and was now removed in the last update). Just to clarify - this issue is superfluous right?

**Comment by han-f** [comment]
yes, thanks @flohrreija-oeko
