### ISSUE TITLE
Two different tutorials have (almost exact) same content 

### ISSUE THREAD

**Issue by vismayajochem** [OpenEnergyPlatform/examples#223]
## Description of the issue
Under others on the OEP there are two identical tutorials (as far as I could tell):
https://openenergyplatform.github.io/academy/tutorials/99_other/OEP_Upload_Process_Data_and_Metadata_oem2orm/ and https://openenergyplatform.github.io/academy/tutorials/99_other/OEP_Upload_Process_Data_and_Metadata_oep-client/. Both can be seen underneath each other. They are exactly the same except that in the latter a 'ModuleNotFoundError' has been included and the last chapter has different code examples.

## Steps to Reproduce

1. See the OEP tutorials listed underneath "other"

## Ideas of solution

Delete the second tutorial https://openenergyplatform.github.io/academy/tutorials/99_other/OEP_Upload_Process_Data_and_Metadata_oep-client/ from the OEP.

## Context and Environment

- Version used:
- Operating system:
- Environment setup and (python) version:

## Workflow checklist

- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/academy/blob/production/CONTRIBUTING.md)

**Comment by christian-rli** [comment]
I checked the tutorials and both of them had several issues. The example data and metadata were no longer available. I reconstructed them from an earlier point in the git history, but neither notebook ran through with the old files provided. Since the oep-client had better descriptions available in the tutorial section, I decided to link to that instead and move the notebook to the legacy folder.

The version focussing on oem2orm had no better description available. Fiddling with the notebook, I was not able to construct a working example. I decided that the notebook as it currently is does more harm than good and also moved it to the legacy folder and removed links to them. When searching for the link to the repository, I stumbled across an unresolved [stackoverflow question](https://stackoverflow.com/questions/75673126/valueerror-dictionary-update-sequence-element-0-has-length-1-2-is-required-d) that builds on the example. 

So technically this solves the issue of two identical and partly broken tutorials and I will therefore close the issue. @jh-RLI this is to inform you that a working documentation/tutorial of oem2orm seems to be missing (as well as an answer to the stackoverflow question).
